package dtu.models;

public enum EventType {
    PAYMENT_REQUEST,
    REFUND_REQUEST,
    RETRIEVE_CUSTOMER,
    RETRIEVE_CUSTOMER_REPORTS,
    RETRIEVE_MERCHANT,
    RETRIEVE_MERCHANT_REPORTS,
    TOKEN_VALIDATION_REQUEST,
    TOKEN_VALIDATION_FAILED,
    MONEY_TRANSFER_FAILED,
    MONEY_TRANSFER_SUCCEED,
    //Token Retrieval
    RETRIEVE_TOKENS,
    RETRIEVE_TOKENS_FAILED,
    RETRIEVE_TOKENS_SUCCEED,
    //Token generation related
    REQUEST_FOR_NEW_TOKENS,
    TOKEN_GENERATION_FAILED,
    TOKEN_GENERATION_SUCCEED
}
