package dtu.models;

/**
 * @author Mathias Hansen s175112
 */

public enum EventType {

    //Retrieve customer profile
    RETRIEVE_CUSTOMER,
    CREATE_CUSTOMER,
    DELETE_CUSTOMER,
    RETRIEVE_CUSTOMER_RESPONSE_SUCCESS,
    RETRIEVE_CUSTOMER_RESPONSE_FAILED,
    DELETE_CUSTOMER_RESPONSE,
    CREATE_CUSTOMER_RESPONSE,
    //Retrieve merchant profile
    RETRIEVE_MERCHANT,
    CREATE_MERCHANT,
    DELETE_MERCHANT,
    RETRIEVE_MERCHANT_RESPONSE_SUCCESS,
    RETRIEVE_MERCHANT_RESPONSE_FAILED,
    DELETE_MERCHANT_RESPONSE,
    CREATE_MERCHANT_RESPONSE,
}
